// ============================================================
// Nifty 50 constituents — NSE ticker symbols
// Static list (updated periodically by NSE). Suffix .NS for Yahoo Finance.
// ============================================================

export const NIFTY_50_TICKERS = [
  "RELIANCE.NS",
  "TCS.NS",
  "HDFCBANK.NS",
  "INFY.NS",
  "ICICIBANK.NS",
  "HINDUNILVR.NS",
  "SBIN.NS",
  "BHARTIARTL.NS",
  "KOTAKBANK.NS",
  "ITC.NS",
  "LT.NS",
  "AXISBANK.NS",
  "BAJFINANCE.NS",
  "ASIANPAINT.NS",
  "MARUTI.NS",
  "HCLTECH.NS",
  "SUNPHARMA.NS",
  "TITAN.NS",
  "TATAMOTORS.NS",
  "ULTRACEMCO.NS",
  "WIPRO.NS",
  "NTPC.NS",
  "POWERGRID.NS",
  "M&M.NS",
  "NESTLEIND.NS",
  "TATASTEEL.NS",
  "JSWSTEEL.NS",
  "ADANIENT.NS",
  "ADANIPORTS.NS",
  "TECHM.NS",
  "BAJAJFINSV.NS",
  "ONGC.NS",
  "COALINDIA.NS",
  "GRASIM.NS",
  "DRREDDY.NS",
  "CIPLA.NS",
  "BPCL.NS",
  "DIVISLAB.NS",
  "EICHERMOT.NS",
  "HEROMOTOCO.NS",
  "APOLLOHOSP.NS",
  "SBILIFE.NS",
  "HDFCLIFE.NS",
  "TATACONSUM.NS",
  "BRITANNIA.NS",
  "BAJAJ-AUTO.NS",
  "INDUSINDBK.NS",
  "HINDALCO.NS",
  "LTIM.NS",
  "SHRIRAMFIN.NS",
  // ── Next 50 additions ──
  "ZOMATO.NS",
  "HAL.NS",
  "BEL.NS",
  "JINDALSTEL.NS",
  "VBL.NS",
  "JIOFIN.NS",
  "IOC.NS",
  "DMART.NS",
  "DLF.NS",
  "BOSCHLTD.NS",
  "PNB.NS",
  "BANKBARODA.NS",
  "TVSMOTOR.NS",
  "HAVELLS.NS",
  "PIDILITIND.NS",
  "AMBUJACEM.NS",
  "SRF.NS",
  "ICICIGI.NS",
  "ICICIPRULI.NS",
  "MUTHOOTFIN.NS",
  "GODREJCP.NS",
  "DABUR.NS",
  "GAIL.NS",
  "VEDL.NS",
  "SHREECEM.NS",
  "SIEMENS.NS",
  "ABB.NS",
  "COLPAL.NS",
  "PGHH.NS",
  "UNITDSPR.NS",
  "INDIGO.NS",
  "ADANIPOWER.NS",
  "ADANIGREEN.NS",
  "ATGL.NS",
  "AWL.NS"
];

// ── Nifty Midcap 150 — representative constituents ──────────
export const NIFTY_MIDCAP_TICKERS = [
  "PERSISTENT.NS",
  "FEDERALBNK.NS",
  "MPHASIS.NS",
  "COFORGE.NS",
  "KALYANKJIL.NS",
  "MARICO.NS",
  "VOLTAS.NS",
  "PIIND.NS",
  "SUNDARMFIN.NS",
  "LUPIN.NS",
  "TORNTPHARM.NS",
  "AAVAS.NS",
  "CHOLAFIN.NS",
  "ABCAPITAL.NS",
  "CAMS.NS",
  "LALPATHLAB.NS",
  "METROPOLIS.NS",
  "TRENT.NS",
  "NAUKRI.NS",
  "MFSL.NS",
  "APLAPOLLO.NS",
  "ASHOKLEY.NS",
  "ESCORTS.NS",
  "JKCEMENT.NS",
  "RAMCOCEM.NS",
  "SUPREMEIND.NS",
  "CROMPTON.NS",
  "DIXON.NS",
  "ATUL.NS",
  "DEEPAKNITR.NS",
  // ── Additional Midcaps ──
  "RECLTD.NS",
  "PFC.NS",
  "CUMMINSIND.NS",
  "OBEROIRLTY.NS",
  "MAZDOCK.NS",
  "RVNL.NS",
  "BHEL.NS",
  "PRESTIGE.NS",
  "NHPC.NS",
  "SJVN.NS",
  "FACT.NS",
  "CGPOWER.NS",
  "BSE.NS",
  "MAXHEALTH.NS",
  "APARINDS.NS",
  "SUZLON.NS",
  "KPRMILL.NS",
  "KPITTECH.NS",
  "TATACOMM.NS",
  "M&MFIN.NS",
  "LODHA.NS",
  "IRFC.NS",
  "AUBANK.NS",
  "IDFCFIRSTB.NS",
  "YESBANK.NS",
  "POONAWALLA.NS",
  "POLYCAB.NS",
  "KEI.NS",
  "KAYNES.NS",
  "IDEA.NS",
  "AARTIIND.NS",
  "SAIL.NS",
  "NMDC.NS",
  "CONCOR.NS",
  "MRF.NS",
  "JUBLFOOD.NS",
  "ASTRAL.NS",
  "IGL.NS",
  "MGL.NS",
  "PETRONET.NS",
  "GUJGASLTD.NS"
];

// ── Nifty Smallcap 250 — representative constituents ────────
export const NIFTY_SMALLCAP_TICKERS = [
  "ROUTE.NS",
  "HAPPYFORGE.NS",
  "ANGELONE.NS",
  "FINEORG.NS",
  "HSCL.NS",
  "SAPPHIRE.NS",
  "CERA.NS",
  "INDIGOPNTS.NS",
  "GANDALF.NS",
  "ELECON.NS",
  "TEJASNET.NS",
  "GRINDWELL.NS",
  "IFCI.NS",
  "RBLBANK.NS",
  "TTKPRESTIG.NS",
  "NOCIL.NS",
  "KRBL.NS",
  "HAPPSTMNDS.NS",
  "DATAPATTNS.NS",
  "KFINTECH.NS",
  "CHALET.NS",
  "SONACOMS.NS",
  "LTTS.NS",
  "CYIENT.NS",
  "NIITLTD.NS",
  "EQUITASBNK.NS",
  "REDINGTON.NS",
  "BALAMINES.NS",
  "PGHL.NS",
  "RKFORGE.NS",
  // ── Additional Smallcaps ──
  "CASTROLIND.NS",
  "CEATLTD.NS",
  "CDSL.NS",
  "RITES.NS",
  "IRCON.NS",
  "J&KBANK.NS",
  "RAYMOND.NS",
  "UCOBANK.NS",
  "IOB.NS",
  "BDL.NS",
  "COCHINSHIP.NS",
  "RAILTEL.NS",
  "TITAGARH.NS",
  "JWL.NS",
  "OLECTRA.NS",
  "NBCC.NS",
  "HUDCO.NS",
  "NCC.NS",
  "MANAPPURAM.NS",
  "IBULHSGFIN.NS",
  "NYKAA.NS",
  "PAYTM.NS",
  "HONASA.NS",
  "ZENTEC.NS",
  "BEML.NS",
  "KIRLOSENG.NS",
  "KIRLOSBROS.NS",
  "TRIVENI.NS",
  "EIDPARRY.NS",
  "BALRAMCHIN.NS",
  "RENUKA.NS",
  "PRAJIND.NS",
  "GNFC.NS",
  "GSFC.NS",
  "CHAMBLFERT.NS",
  "RCF.NS",
  "NATCOPHARM.NS",
  "GLENMARK.NS",
  "LAURUSLABS.NS",
  "GRANULES.NS",
  "JBCHEPHARM.NS",
  "CAPLIPOINT.NS",
  "THYROCARE.NS",
  "IEX.NS",
  "MCX.NS"
];

// Top-performing MF scheme codes (AMFI) — curated large-cap, flexi-cap & index funds
export const TOP_MF_SCHEMES = [
  { code: "120503", name: "Axis Bluechip Fund" },
  { code: "120505", name: "Mirae Asset Large Cap Fund" },
  { code: "118989", name: "Parag Parikh Flexi Cap Fund" },
  { code: "122639", name: "SBI Bluechip Fund" },
  { code: "120587", name: "HDFC Flexi Cap Fund" },
  { code: "135781", name: "UTI Nifty 50 Index Fund" },
  { code: "120716", name: "Kotak Equity Opp Fund" },
  { code: "119597", name: "ICICI Pru Bluechip Fund" },
  { code: "125497", name: "Motilal Oswal Nifty 50 Index Fund" },
  { code: "118834", name: "Canara Robeco Bluechip Fund" },
];

// ── Top ETF Tickers (50 Liquid ETFs across categories) ──────────
export const TOP_ETF_TICKERS = [
  // Broad Market (Large Cap)
  "NIFTYBEES.NS",
  "SETFNIF50.NS",
  "ICICINIFTY.NS",
  "HDFCNIFTY.NS",
  "KOTAKNIFTY.NS",
  "AXISNIFTY.NS",
  "BSLNIFTY.NS",
  "MOM50.NS",
  
  // Broad Market (Mid Cap & Next 50)
  "JUNIORBEES.NS",
  "ICICINXT50.NS",
  "SETFNN50.NS",
  "MID150BEES.NS",
  "ICICIMCAP.NS",
  
  // Sectoral - Banking & Financials
  "BANKBEES.NS",
  "SETFNIFBK.NS",
  "KOTAKBKETF.NS",
  "PSUBNKBEES.NS",
  "KOTAKPSUBK.NS",
  "HDFCNIFBK.NS",
  "PVTBANIETF.NS",

  // Sectoral - IT, Pharma, Auto, FMCG & Others
  "ITBEES.NS",
  "ICICITECH.NS",
  "KOTAKIT.NS",
  "NETFIT.NS",
  "PHARMABEES.NS",
  "ICICIPHARM.NS",
  "AUTOBEES.NS",
  "FMCGIETF.NS",
  "CONSUMBEES.NS",
  "INFRABEES.NS",
  "HEALTHY.NS",
  
  // Thematic & Smart Beta
  "CPSEETF.NS",
  "ICICIB22.NS",
  "MAKEINDIA.NS",
  "NV20BEES.NS",
  "LOWVOLIETF.NS",
  "MOM30IETF.NS",
  "ALPHIETF.NS",
  "QUAL30IETF.NS",
  "DIVOPPIETF.NS",

  // Commodities (Gold & Silver)
  "GOLDBEES.NS",
  "GOLDIETF.NS",
  "HDFCGOLD.NS",
  "SILVERBEES.NS",
  "SILVERIETF.NS",

  // International
  "MON100.NS",
  "MASPTOP50.NS",
  "HNGSNGBEES.NS",
  
  // Debt / Liquid
  "LIQUIDBEES.NS",
  "GILT5YBEES.NS",
];
