// ============================================================
// Nifty 50 constituents — NSE ticker symbols
// Static list (updated periodically by NSE). Suffix .NS for Yahoo Finance.
// ============================================================

export const NIFTY_50_TICKERS = [
  "RELIANCE.NS",
  "TCS.NS",
  "HDFCBANK.NS",
  "INFY.NS",
  "ICICIBANK.NS",
  "HINDUNILVR.NS",
  "SBIN.NS",
  "BHARTIARTL.NS",
  "KOTAKBANK.NS",
  "ITC.NS",
  "LT.NS",
  "AXISBANK.NS",
  "BAJFINANCE.NS",
  "ASIANPAINT.NS",
  "MARUTI.NS",
  "HCLTECH.NS",
  "SUNPHARMA.NS",
  "TITAN.NS",
  "TATAMOTORS.NS",
  "ULTRACEMCO.NS",
  "WIPRO.NS",
  "NTPC.NS",
  "POWERGRID.NS",
  "M&M.NS",
  "NESTLEIND.NS",
  "TATASTEEL.NS",
  "JSWSTEEL.NS",
  "ADANIENT.NS",
  "ADANIPORTS.NS",
  "TECHM.NS",
  "BAJAJFINSV.NS",
  "ONGC.NS",
  "COALINDIA.NS",
  "GRASIM.NS",
  "DRREDDY.NS",
  "CIPLA.NS",
  "BPCL.NS",
  "DIVISLAB.NS",
  "EICHERMOT.NS",
  "HEROMOTOCO.NS",
  "APOLLOHOSP.NS",
  "SBILIFE.NS",
  "HDFCLIFE.NS",
  "TATACONSUM.NS",
  "BRITANNIA.NS",
  "BAJAJ-AUTO.NS",
  "INDUSINDBK.NS",
  "HINDALCO.NS",
  "LTIM.NS",
  "SHRIRAMFIN.NS",
];

// ── Nifty Midcap 150 — representative constituents ──────────
export const NIFTY_MIDCAP_TICKERS = [
  "PERSISTENT.NS",
  "FEDERALBNK.NS",
  "MPHASIS.NS",
  "COFORGE.NS",
  "KALYANKJIL.NS",
  "MARICO.NS",
  "VOLTAS.NS",
  "PIIND.NS",
  "SUNDARMFIN.NS",
  "LUPIN.NS",
  "TORNTPHARM.NS",
  "AAVAS.NS",
  "CHOLAFIN.NS",
  "ABCAPITAL.NS",
  "CAMS.NS",
  "LALPATHLAB.NS",
  "METROPOLIS.NS",
  "TRENT.NS",
  "NAUKRI.NS",
  "MFSL.NS",
  "APLAPOLLO.NS",
  "ASHOKLEY.NS",
  "ESCORTS.NS",
  "JKCEMENT.NS",
  "RAMCOCEM.NS",
  "SUPREMEIND.NS",
  "CROMPTON.NS",
  "DIXON.NS",
  "ATUL.NS",
  "DEEPAKNITR.NS",
];

// ── Nifty Smallcap 250 — representative constituents ────────
export const NIFTY_SMALLCAP_TICKERS = [
  "ROUTE.NS",
  "HAPPYFORGE.NS",
  "ANGELONE.NS",
  "FINEORG.NS",
  "HSCL.NS",
  "SAPPHIRE.NS",
  "CERA.NS",
  "INDIGOPNTS.NS",
  "GANDALF.NS",
  "ELECON.NS",
  "TEJASNET.NS",
  "GRINDWELL.NS",
  "IFCI.NS",
  "RBLBANK.NS",
  "TTKPRESTIG.NS",
  "NOCIL.NS",
  "KRBL.NS",
  "HAPPSTMNDS.NS",
  "DATAPATTNS.NS",
  "KFINTECH.NS",
  "CHALET.NS",
  "SONACOMS.NS",
  "LTTS.NS",
  "CYIENT.NS",
  "NIITLTD.NS",
  "EQUITASBNK.NS",
  "REDINGTON.NS",
  "BALAMINES.NS",
  "PGHL.NS",
  "RKFORGE.NS",
];

// Top-performing MF scheme codes (AMFI) — curated large-cap, flexi-cap & index funds
export const TOP_MF_SCHEMES = [
  { code: "120503", name: "Axis Bluechip Fund" },
  { code: "120505", name: "Mirae Asset Large Cap Fund" },
  { code: "118989", name: "Parag Parikh Flexi Cap Fund" },
  { code: "122639", name: "SBI Bluechip Fund" },
  { code: "120587", name: "HDFC Flexi Cap Fund" },
  { code: "135781", name: "UTI Nifty 50 Index Fund" },
  { code: "120716", name: "Kotak Equity Opp Fund" },
  { code: "119597", name: "ICICI Pru Bluechip Fund" },
  { code: "125497", name: "Motilal Oswal Nifty 50 Index Fund" },
  { code: "118834", name: "Canara Robeco Bluechip Fund" },
];
